<?php

namespace AppBundle\Repository;

/**
 * GamePlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePlatformRepository extends \Doctrine\ORM\EntityRepository
{
}
