<?php

namespace AppBundle\Repository;

/**
 * PlatformAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformAliasRepository extends \Doctrine\ORM\EntityRepository
{
}
