<?php

namespace AppBundle\Repository;

/**
 * StreamEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
