<?php

namespace AppBundle\Repository;

/**
 * StrikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrikeRepository extends \Doctrine\ORM\EntityRepository
{
}
