app:
    resource: "@AppBundle/Controller/"
    type:     annotation
logout:
    path: /logout

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admincp

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admincp

presta_image:
    resource: "@PrestaImageBundle/Resources/config/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
